### ISSUE TITLE
[feat] Custom time

### ISSUE THREAD

**Issue by RSS1102** [prazdevs/potato-timer#2]
Would it be better if you could customize the time?
If the custom time is through sliding the progress bar, is it more cool!!
![image](https://user-images.githubusercontent.com/81673017/221737398-2058f408-c247-4140-9c9b-0a2f1e5a1d1c.png)

**Comment by prazdevs** [comment]
what do you mean by customize time ? You can change timers in the small cog button (the 3rd one) when the timer is stopped :)

**Comment by RSS1102** [comment]
> 自定义时间是什么意思？当计时器停止时，您可以在小齿轮按钮（第 3 个）中更改计时器 :)
My error, I didn't see the **setting button** on the right:laughing:
